app_home:
    path: /
    controller: App\Controller\CoreController::index

app_lirecsv:
    path: /lirecsv
    controller: App\Controller\CoreController::lirecsv

app_calculgroupe:
    path: /calculgroupe
    controller: App\Controller\CoreController::calculgroupe