app_home:
    path: /
    controller: App\Controller\CoreController::index

app_superadmin_config:
    path: /superadmin/config
    controller: App\Controller\SuperadminController::config

app_admin_accueil:
    path: /admin/accueil
    controller: App\Controller\AdminController::accueil

app_admin_initialisation:
    path: /admin/initialisation
    controller: App\Controller\AdminController::initialisation

app_admin_reinitialisation:
    path: /admin/reinitialisation
    controller: App\Controller\AdminController::reinitialisation

app_admin_parametrage_eleves:
    path: /admin/parametrage/eleves
    controller: App\Controller\AdminController::eleves

app_admin_parametrage_eleves_etape1:
    path: /admin/parametrage/eleves/etape1
    controller: App\Controller\AdminController::etape1

app_admin_parametrage_eleves_etape2:
    path: /admin/parametrage/eleves/etape2
    controller: App\Controller\AdminController::etape2

app_admin_parametrage_eleves_etape3:
    path: /admin/parametrage/eleves/etape3
    controller: App\Controller\AdminController::etape3

app_admin_parametrage_eleves_etape4:
    path: /admin/parametrage/eleves/etape4
    controller: App\Controller\AdminController::etape4

app_admin_parametrage_ateliers:
    path: /admin/parametrage/ateliers
    controller: App\Controller\AtelierController::ateliers

app_admin_parametrage_ateliers_ajoute:
    path: /admin/parametrage/ateliers/ajoute
    controller: App\Controller\AtelierController::ateliers_ajoute

app_admin_parametrage_ateliers_modifie:
    path: /admin/parametrage/ateliers/modifie/{id}
    controller: App\Controller\AtelierController::ateliers_modifie
    requirements:
        id: \d*

app_admin_parametrage_ateliers_supprime:
    path: /admin/parametrage/ateliers/supprime/{id}
    controller: App\Controller\AtelierController::ateliers_supprime
    requirements:
        id: \d*

app_admin_parametrage_salles:
    path: /admin/parametrage/salles
    controller: App\Controller\SalleController::salles

app_admin_parametrage_salles_ajoute:
    path: /admin/parametrage/salles/ajoute
    controller: App\Controller\SalleController::salles_ajoute

app_admin_parametrage_salles_modifie:
    path: /admin/parametrage/salles/modifie/{id}
    controller: App\Controller\SalleController::salles_modifie
    requirements:
        id: \d*

app_admin_parametrage_salles_supprime:
    path: /admin/parametrage/salles/supprime/{id}
    controller: App\Controller\SalleController::salles_supprime
    requirements:
        id: \d*

app_admin_parametrage_horaires:
    path: /admin/parametrage/horaires
    controller: App\Controller\HoraireController::horaires

app_admin_parametrage_horaires_ajoute:
    path: /admin/parametrage/horaires/ajoute
    controller: App\Controller\HoraireController::horaires_ajoute

app_admin_parametrage_horaires_modifie:
    path: /admin/parametrage/horaires/modifie/{id}
    controller: App\Controller\HoraireController::horaires_modifie
    requirements:
        id: \d*

app_admin_parametrage_horaires_supprime:
    path: /admin/parametrage/horaires/supprime/{id}
    controller: App\Controller\HoraireController::horaires_supprime
    requirements:
        id: \d*

app_admin_parametrage_intervenants:
    path: /admin/parametrage/intervenants
    controller: App\Controller\IntervenantController::intervenants

app_admin_parametrage_intervenants_ajoute:
    path: /admin/parametrage/intervenants/ajoute
    controller: App\Controller\IntervenantController::intervenants_ajoute

app_admin_parametrage_intervenants_modifie:
    path: /admin/parametrage/intervenants/modifie/{id}
    controller: App\Controller\IntervenantController::intervenants_modifie
    requirements:
        id: \d*

app_admin_parametrage_intervenants_supprime:
    path: /admin/parametrage/intervenants/supprime/{id}
    controller: App\Controller\IntervenantController::intervenants_supprime
    requirements:
        id: \d*

app_admin_inscriptions:
    path: /admin/inscriptions
    controller: App\Controller\InscriptionController::index

app_admin_inscriptions_start:
    path: /admin/inscriptions/start
    controller: App\Controller\InscriptionController::start

app_admin_parametragegroupes:
    path: /admin/parametrage/groupes
    controller: App\Controller\AdminController::ateliers

app_getprogress:
    path: /getprogress
    controller: App\Controller\ProgressController::getProgress

app_etape1:
    path: /admin/import/etape1
    controller: App\Controller\ImportController::etape1

app_etape2:
    path: /admin/import/etape2
    controller: App\Controller\ImportController::etape2

app_etape3:
    path: /admin/import/etape3
    controller: App\Controller\ImportController::etape3

app_etape4:
    path: /admin/import/etape4
    controller: App\Controller\ImportController::etape4

app_resultats_csv_secretariat:
    path: /admin/import/app_resultats_csv_secretariat
    controller: App\Controller\ImportController::retourner_csv_secretariat

app_logout:
    path: /logout