app_home:
    path: /
    controller: App\Controller\CoreController::index

app_getprogress:
    path: /getprogress
    controller: App\Controller\ProgressController::getProgress

app_etape2:
    path: /etape2
    controller: App\Controller\CoreController::etape2

app_etape3:
    path: /etape3
    controller: App\Controller\CoreController::etape3

app_etape4:
    path: /etape4
    controller: App\Controller\CoreController::etape4

app_ajoute:
    path: /ajoute/{id}
    controller: App\Controller\CoreController::ajoute

app_retire:
    path: /retire/{id}
    controller: App\Controller\CoreController::retire
    requirements:
        id:   \d+

app_resultats_csv_secretariat:
    path: /app_resultats_csv_secretariat
    controller: App\Controller\CoreController::retourner_csv_secretariat
